server_port: 8088
log_path: runtime/logs/

mysql_dsn: nablegin:123456@tcp(127.0.0.1:3306)/nablegin?charset=utf8&parseTime=true&loc=Local
mysql_max_idle: 10
mysql_max_open: 100

redis_addr: 127.0.0.1:6379
redis_db: 0
redis_max_idle: 10
redis_max_open: 100

admin_title : NABLEPRO后端管理平台